name: CI

on:
  push:
    branches:
      - ci-workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          git config --global user.email "elan.hamburger@gmail.com"
          git config --global user.name "Elan Hamburger"
          git add -f build
          git commit -m "Deploy of commit ${GITHUB_SHA:0:7}"
          git push https://github.com/$GITHUB_REPOSITORY `git subtree split --prefix build master`:gh-pages --force
